# Run Jupyter notebook in a workflow
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: jupyter
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: jupyter/scipy-notebook:lab-3.2.9
        command: [sh, -c]
        args: ["python3 -m jupyterlab --host 0.0.0.0 --LabApp.token=''"]
